controller:
  serviceType: ClusterIP   # 👈 aquí sí se usa serviceType
  adminUser: admin
  adminPassword: supersecret

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

persistence:
  enabled: true
  size: 8Gi
