service:
  type: ClusterIP  # 👈 clave correcta
  ports:
    http: 80
    https: 443

jenkinsUser: admin
jenkinsPassword: supersecret

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
