controller:
  serviceType: ClusterIP   # 👈 aquí sí se usa serviceType
  adminUser: admin
  adminPassword: supersecret
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest

  # 👇 Corrección de permisos
  runAsUser: 1000
  fsGroup: 1000

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  
persistence:
  enabled: true
  size: 8Gi
