apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pedido-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JoseSantacruz12000/Prueba-Trabajo-K8s.git   # tu repo
    targetRevision: HEAD                                 # rama (main, HEAD o tag)
    path: charts/pedido-app                              # ruta al chart padre
    helm:
      valueFiles:
        - values.yaml                                    # usa tu values.yaml del chart padre
  destination:
    server: https://kubernetes.default.svc
    namespace: my-tech                                   # namespace destino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
