apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: 5.8.86
    chart: jenkins
    helm:
      valuesObject:
        controller:
          serviceType: ClusterIP   # 👈 aquí sí se usa serviceType
          admin:
            username: admin
            password: supersecret
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
        volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - PruneLast=true
