apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: 5.8.86
    helm:
      valueFiles:
        - values.yaml
    chart: jenkins
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - PruneLast=true
